pipeline {
    agent {
        docker {
            image 'node:6-alpine' 
            args '-p 3000:3000' 
        }
    }

    environment {
        // Define your Nexus IQ server credentials and URLs
        NEXUS_IQ_SERVER_URL = credentials('NEXUS_IQ_SERVER_URL')
        NEXUS_IQ_CREDS = credentials('NEXUS_IQ_CREDENTIALS')
        NEXUS_IQ_APPLICATION_ID = 'TEST_WEB_APP'
    }

    stages {
        stage('Checking application ID in Sonatype Server') {
            steps {
                echo "Checking application ID in Sonatype Server: $NEXUS_IQ_SERVER_URL"
            }
        }

        stage('Install Frontend Dependencies') {
            steps {
                dir('frontend') {
                    sh 'npm install'
                }
            }
        }

        stage('Install Backend Dependencies') {
            steps {
                dir('backend') {
                    sh 'npm install'
                }
            }
        }
    }
}
