pipeline {
    agent any

    environment {
        /*
        HTTP_PROXY = credentials(HTTP_PROXY)
        HTTPS_PROXY = credentials(HTTPS_PROXY)
        NO_PROXY = credentials(NO_PROXY)

        // Define your Nexus IQ server credentials and URLs
        NEXUS_IQ_SERVER_URL = env.NEXUS_IQ_SERVER_URL

        NEXUS_IQ_USERNAME = credentials(NEXUS_IQ_USERNAME)
        NEXUS_IQ_PASSWORD = credentials(NEXUS_IQ_PASSWORD)
        */
        
        NEXUS_IQ_SERVER_URL = credentials(NEXUS_IQ_SERVER_URL)
        NEXUS_IQ_APPLICATION_ID = 'TEST_WEB_APP'
    }

    stages {
        /*
        stage('Checking application ID in Sonatype Server') {
            steps {
                echo "Checking application ID in Sonatype Server: $NEXUS_IQ_SERVER_URL"
            }
        }
        */

        stage('Pull and Scan Docker Images w/o Async or //') {
            steps {
                script {
                    def startTime = currentBuild.startTimeInMillis

                    def endTime = currentBuild.startTimeInMillis
                    def totalTime = endTime - startTime

                    echo "Total execution time without async/parallel: ${totalTime} ms"
                }
            }
        }
    }
}
