pipeline {
    agent any

    environment {
        HTTP_PROXY = credentials('HTTP_PROXY')
        HTTPS_PROXY = credentials('HTTPS_PROXY')
        NO_PROXY = credentials('NO_PROXY')
        
        // Define your Nexus IQ server credentials and URLs
        NEXUS_IQ_SERVER_URL = credentials('NEXUS_IQ_SERVER_URL')
        NEXUS_IQ_CREDS = credentials('NEXUS_IQ_CREDENTIALS')
        NEXUS_IQ_APPLICATION_ID = 'TEST_WEB_APP'
    }

    stages {
        stage('Install nvm and Node.js') {
            steps {
                // Install nvm
                sh 'curl https://raw.githubusercontent.com/creationix/nvm/master/install.sh | bash'

                // Source nvm to make it available in this shell
                sh 'source ~/.nvm/nvm.sh'

                sh 'nvm install node'
            }
        }

        stage('Install Frontend Dependencies') {
            steps {
                dir('frontend') {
                    sh 'npm install'
                }
            }
        }

        stage('Install Backend Dependencies') {
            steps {
                dir('backend') {
                    sh 'npm install'
                }
            }
        }

        stage('Checking application ID in Sonatype Server') {
            steps {
                echo "Checking application ID in Sonatype Server: $NEXUS_IQ_SERVER_URL"
            }
        }    
    }
}
